---
title: "Explanatory Analysis"
format: html
editor: source
---

## Initialization

### Libraries
```{r}
library(tidyverse)
library(patchwork)
```

### Dataframe
```{r}
df <- read.csv2("../exploratory_analysis/df_processed.csv") %>%
  rename(
    ethnicity = RIDRETH1,
    age = RIDAGEYR,
    gender = RIAGENDR,
    edlevel = DMDEDUC2 # educational level
    )
head(df)
```

### Labels
```{r}
ethnicity_labels <- c(
  "Mexican American",
  "Other Hispanic",
  "Non-Hispanic White",
  "Non-Hispanic Black",
  "Other Race / Multi-Racial")

diagnosed_labels <- c("Undiagnosed / Not aware", "Diagnosed / aware")

insurance_labels <- c("Uninsured", "Insured")

biomarker_labels <- c("Negative", "Positive")

risk_levels <- c(
  "Low",
  "Moderate",
  "High",
  "Very High",
  "Highest")

age_levels <- c(
  "18–39",
  "40–59",
  "60–79",
  "≥80"
)

poverty_levels <- c(
  "Poor",
  "Near Poor",
  "Middle Class",
  "Affluent"
)

code_colors <- c(
  "Low" =       "#4CAF50",  # Green
  "Moderate" =  "#FFEB3B",  # Yellow
  "High" =      "#FF9800",  # Orange
  "Very High" = "#F44336",  # Red
  "Highest" =   "#8B0000"   # Dark Red/Wine
)
```


### Categorize
```{r}
df_viz <- df %>%
  mutate(
    ethnicity = factor(ethnicity, labels = ethnicity_labels),
    ckd_diagnosed = factor(ckd_diagnosed, labels = diagnosed_labels),
    hinsu_covered = factor(hinsu_covered, labels = insurance_labels),
    ckd_biomarker = factor(ckd_biomarker, labels = biomarker_labels),
    egfr_cat = factor(egfr_cat),
    age_cat = factor(age_cat, levels = age_levels), # Necessary to add levels to reorder
    uacr_cat = factor (uacr_cat),
    ckd_risk = factor(ckd_risk, levels = risk_levels),
    poverty_cat = cut(INDFMPIR,
                        breaks = c(-Inf, 1, 3, 4.98, Inf),
                        labels = poverty_levels)
  )

head(df_viz)
```


```{r}
df_viz %>%
  filter(ckd_biomarker == "Positive") %>%
  head()
```

### Theme Infography
```{r}
dashboard_theme <- theme_minimal(base_size = 14) +
  theme(
    # 1. Graph Title
    plot.title = element_text(
      family = "sans",
      face = "bold",
      size = 22,
      hjust = 0, # Left align
      margin = margin(b = 10) # Lower margin
      
    ),
    
    # 2. Graph Subtitle
    plot.subtitle = element_text(
      family = "sans",
      size = 18,
      color = "grey30",     # Grey better than black
      margin = margin(b = 10)
    ),
    
    # 3. Axis titles
    axis.title = element_text(
      family = "sans",
      face = "bold",
      size = 16
    ),
    axis.text = element_text(
      family = "sans",
      size = 14
    ),
    
    # 4. Legends
    legend.title = element_text(face = "bold", size = 18),
    legend.text = element_text(size = 16),
    
    panel.grid.minor = element_blank()
  )
```

## Exploratory Analysis

```{r population_distribution_ckd_risk}
risk_distribution <- df_viz %>%
  count(ckd_risk) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
  
  ggplot(
    aes(
      x = ckd_risk,
      y = pct,
      fill = ckd_risk)
  ) +
  
  geom_col(
    width = 0.7,
    color = "white"
  ) +
  
  geom_text(
    aes(label = label_text),
    vjust = -0.5,
    size = 3.5,
    fontface = "bold"
  ) +
  
  scale_fill_manual(
    values = code_colors
  ) +
  
  ylim(0, 100) +
  
  labs(
    title = "Population Distribution by CKD Risk",
    subtitle = "Percentage of total population in each risk category",
    y = "Proportion (%)", 
    x = NULL
  ) +
  
  theme_minimal(base_size = 14) +
  
  theme(legend.position = "none", # No legend needed because the bars already say what they are.
        panel.grid.major.x = element_blank(), # Delete x grid
        plot.title = element_text(face = "bold") # Bold title
  ) 

risk_distribution
```

```{r risk_progression_age}
age_risk <- df_viz %>%
  count(age_cat, ckd_risk) %>%
  group_by(age_cat) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
  
  ggplot(
    aes(
      x = age_cat,
      y = pct,
      fill = ckd_risk)
  ) +
  
  geom_col(
    position = position_dodge(width = 0.9),
    width = 0.8
  ) +
  
  scale_fill_manual(
    values = code_colors
  ) +
  
  ylim(0, 100.1) +
  
  theme_minimal(base_size = 12) +
  
  labs(
    title = "Risk Progression by Age",
    subtitle = "Higher risk categories increase significantly with age",
    y = "Proportion (%)", 
    x = "Age (years)",
    fill = "CKD Risk"
  ) +
  
  theme(
    panel.grid.major.x = element_blank(),
    plot.title = element_text(face = "bold")
  )

age_risk
```

```{r risk_progression_ethnicity}
ethnicity_risk <- df_viz %>%
  count(ethnicity, ckd_risk) %>%
  group_by(ethnicity) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
  
  ggplot(
    aes(
      y = ethnicity,
      x = pct,
      fill = ckd_risk)
  ) +
  
  geom_col(
    position = position_dodge(width = 0.9),
    width = 0.8
  ) +
  
  scale_fill_manual(
    values = code_colors
  ) +
  
  xlim(0, 100.1) +
  
  theme_minimal(base_size = 12) +
  
  labs(
    title = "Risk Progression by Ethinicity",
    subtitle = "No correlation among risk categories and ethnicity",
    x = "Proportion (%)", 
    y = "Ethnicity",
    fill = "CKD Risk"
  ) +
  
  theme(
    panel.grid.major.x = element_blank(),
    plot.title = element_text(face = "bold")
  )

ethnicity_risk
```

## Panel 3

```{r population_ckd_risk}
egfr_uacr_density <- df_viz %>%
  ggplot(aes(x = egfr_value, y = uacr_value)) +
  annotate("rect", xmin = 60, xmax = Inf, ymin = 0, ymax = 300, fill = "grey93", alpha = 0.8) + # grey background
  annotate("rect", xmin = 45, xmax = 60, ymin = 0, ymax = 30, fill = "grey93", alpha = 0.8) +   # grey background
  geom_point(aes(color = ckd_diagnosed), size = 2.5, alpha = 0.5) +
  
  # threshold lines
  annotate("segment", x = 60, xend = Inf, y = 300, yend = 300, color = "black", linewidth = 0.8, linetype = "dashed") +
  annotate("segment", x = 60, xend = 60, y = 30, yend = 300, color = "black", linewidth = 0.8, linetype = "dashed") +
  annotate("segment", x = 45, xend = 60, y = 30, yend = 30, color = "black", linewidth = 0.8, linetype = "dashed") +
  annotate("segment", x = 45, xend = 45, y = 0, yend = 30, color = "black", linewidth = 0.8, linetype = "dashed") +
  
  # Text "High CKD risk threshold"
  annotate("text", x = 170, y = 900, label = "High CKD \nrisk threshold", 
           size = 7, fontface = "bold", color = "black", hjust = 0.5) +
  
  scale_y_log10(limits = c(1, NA)) + 
  scale_color_manual(name = "CKD Status", 
                     values = c("Undiagnosed / Not aware" = "salmon", 
                                "Diagnosed / aware" = "mediumturquoise")) +
  labs(title = "CKD Risk on the population", subtitle = "uACR ~ eGFR Correlation", x = "eGFR (mL/min)", y = "uACR (mg/g) [log]") + 
  dashboard_theme + 
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 18, face = "bold"),
    legend.text = element_text(size = 16),
    legend.key.size = unit(1.5, "cm")
  ) +
  # This specific command increases the size of the dots ONLY in the legend.
  guides(color = guide_legend(override.aes = list(size = 6, alpha = 1)))

egfr_uacr_density
```


```{r diagnostic_gap}
diagnostic_gap <- df_viz %>%
  filter(ckd_biomarker == "Positive") %>%
  count(ckd_diagnosed) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
  
  ggplot(
    aes(
      x = 2,
      y = pct,
      fill = ckd_diagnosed
    )
  ) +
  
  geom_col(
    color = "white"
  ) +
  
  coord_polar(theta = "y") +
  
  xlim(0.5, 2.5) +
  
  geom_text(
    aes(label = label_text),
    position = position_stack(vjust = 0.5),
    color = "white", fontface = "bold", size = 5
  ) +
  
  labs(
    title = "Diagnostic Gap ",
    subtitle = "with biological evidence of CKD (positive CKD biomarker)"
  ) +
  
  theme_void() +
  
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "bottom",
    legend.title = element_blank()
  )
  
diagnostic_gap
```

```{r}
panel_1 <- ggplot() +
  annotate("text", x = 0.5, y = 0.8, label = "6%", size = 16, fontface = "bold", color = "black", hjust = 0.5) +
  annotate("text", x = 0.5, y = 0.15, label = "\nof population at\nhigh risk of CKD", size = 7, lineheight = 0.85, color = "grey20", hjust = 0.5) +
  xlim(-0.4, 1.4) + ylim(-0.4, 1.4) +
  theme_void() + 
  theme(plot.background = element_rect(fill = NA, color = "black", linewidth = 1.2),
        plot.margin = margin(30, 20, 30, 20))


panel_2 <- ggplot() +
  annotate("text", x = 0.5, y = 0.72, label = "74%", size = 16, fontface = "bold", color = "salmon", hjust = 0.5) +
  annotate("text", x = 0.5, y = 0.20, label = "\nof them are not \naware or diagnosed", size = 7, lineheight = 0.85, color = "grey20", hjust = 0.5) +
  xlim(-0.2, 1.2) + ylim(-0.2, 1.2) +
  theme_void() + 
  theme(plot.background = element_rect(fill = NA, color = "black", linewidth = 1.2),
        plot.margin = margin(30, 20, 30, 20))


key_findings_combined <- (plot_spacer() / panel_1 / plot_spacer() / panel_2 / plot_spacer()) + 
  plot_layout(heights = c(0.8, 1, 0.4, 1, 0.8))


d1_layout <- "
AAAA#
AAAAB
AAAA#
AAAAC
AAAA#
"

row_heights <- c(1,1,0.25,1)

d1 <-
  
  wrap_elements(
    egfr_uacr_density +
    dashboard_theme +
    theme(
      legend.position = "bottom"
    )
  ) + #A
  
  wrap_elements(panel_1 +
    dashboard_theme +
    theme(
      panel.grid = element_blank(),
      axis.text = element_blank()
    )
  ) + #B
  
  wrap_elements(panel_2 +
    dashboard_theme +
    theme(
      panel.grid = element_blank(),
      axis.text = element_blank()
    )
  ) + #C
  
  plot_layout(design = d1_layout, heights = row_heights) +
  
  plot_annotation(
    title = "The Diagnostic Gap",
    subtitle = "Most individuals with biological evidence of CKD are unaware of their condition",
    caption = "Source: NHANES 2007-2018",
    theme = theme(
      plot.title = element_text(size = 26, face = "bold", color = "#2C3E50"),
      plot.subtitle = element_text(size = 20, color = "grey40", margin = margin(b = 20))
    )
  )

ggsave(
  filename = "../infography/panel1_diagnostic_gap.png",
  plot = d1,
  width = 16,
  height = 9,
  dpi = 300,
  bg = "white"
)
```

## Panel 2

```{r dg_ethnicity}
ethnicity_gap <- df_viz %>%
  filter(ckd_biomarker == "Positive") %>%
  group_by(ethnicity) %>%
  count(ckd_diagnosed) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
filter(ckd_diagnosed == "Undiagnosed / Not aware") %>%
  
  ggplot(
    aes(
      x = pct,
      y = ethnicity,
      fill = 'salmon'
    )
  ) +
  
  geom_col(
    alpha = 0.4,
    width = 0.6,
    color = 'black'
  ) +
  
  geom_text(
    aes(label = label_text),
    hjust = -0.5,
    size = 3.5,
    fontface = "bold",
    color = 'black'
  ) +
  
  xlim(0, 100) +
  
  labs(
    title = "Diagnostic Gap: Ethnicity",
    subtitle = "with biological evidence of CKD - positive CKD biomarker",
    x = "Proportion (%)", 
    y = NULL
  ) +
  
  theme_minimal(base_size = 14) +
  
  theme(legend.position = "none",
        panel.grid.major.y = element_blank(),
        plot.title = element_text(face = "bold") # Bold title
  )
  
ethnicity_gap
```


```{r dg_insurance}
insurance_gap <- df_viz %>%
  filter(ckd_biomarker == "Positive") %>%
  group_by(hinsu_covered) %>%
  count(ckd_diagnosed) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
filter(ckd_diagnosed == "Undiagnosed / Not aware") %>%
  
  ggplot(
    aes(
      y = pct,
      x = hinsu_covered,
      fill = 'salmon'
    )
  ) +
  
  geom_col(
    alpha = 0.8,
    width = 0.6,
    color = 'black'
  ) +
  
  geom_text(
    aes(label = label_text),
    vjust = -0.5,
    size = 7,
    fontface = "bold",
    color = 'black'
  ) +
  
  ylim(0, 100) +
  
  labs(
    title = "Diagnostic Gap: Insurance status",
    subtitle = "with biological evidence of CKD",
    y = NULL, 
    x = NULL
  ) +
  
  theme_minimal(base_size = 14) +
  
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        plot.title = element_text(face = "bold"), # Bold title
        axis.text.y = element_blank()
  )
  
insurance_gap
```

```{r dg_poverty}
poverty_gap <- df_viz %>%
  filter(ckd_biomarker == "Positive") %>%
  filter(!is.na(poverty_cat)) %>%
  group_by(poverty_cat) %>%
  count(ckd_diagnosed) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
  filter(ckd_diagnosed == "Undiagnosed / Not aware") %>%

  
  ggplot(
    aes(
      x = pct,
      y = poverty_cat,
      fill = 'salmon'
    )
  ) +
  
  geom_col(
    alpha = 0.4,
    width = 0.5,
    color = 'black'
  ) +
  
  geom_text(
    aes(label = label_text),
    hjust = -0.5,
    size = 3.5,
    fontface = "bold",
    color = 'black'
  ) +
  
  xlim(0, 100) +

  labs(
    title = "Diagnostic Gap: Poverty",
    subtitle = "with biological evidence of CKD - positive CKD biomarker",
    x = "Proportion (%)", 
    y = NULL
  ) +
  
  theme_minimal(base_size = 14) +
  
  theme(legend.position = "none",
        panel.grid.major.y = element_blank(),
        plot.title = element_text(face = "bold") # Bold title
  )
  
poverty_gap
```


```{r structural_barriers}
heatmap <- df_viz %>%
  filter(ckd_biomarker == "Positive") %>%
  filter(!is.na(poverty_cat)) %>%
  group_by(poverty_cat, ethnicity) %>%
  count(hinsu_covered) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
  filter(hinsu_covered == "Uninsured") %>%
  
  ggplot(
    aes(
      x = poverty_cat,
      y = ethnicity,
      fill = pct
    )
  ) +
  
  geom_tile(
    color = "white",
    size = 0.5
  ) +
  
  # geom_text(
  #   aes(label = label_text),
  #   color = "black", size = 4
  # ) +
  

  scale_fill_distiller(
    palette = "Blues",
    direction = 1,
    labels = scales::label_number(suffix = "%")
  ) +
  
  labs(
    title = "Structural Barriers: Lack of Health Insurance",
    subtitle = "Uninsured individuals by Poverty Level and Ethnicity",
    y = NULL,
    x = "Poverty",
    fill = "% Uninsured"
  ) +
  
  
  theme_minimal(base_size = 14) +
  
  theme(
    plot.title = element_text(face = "bold"),
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 0),
    legend.position = "top",
    legend.justification = "center",
    legend.key.width = unit(2, "cm")
  )

heatmap
```


```{r}
d2_layout <- "
ABBBB
"

d2 <- 
  wrap_elements(
    (insurance_gap +
      dashboard_theme +
      scale_y_discrete(labels = insurance_labels) + 
      labs(subtitle = NULL) +
      ylim(0,90) +
      theme(
        panel.grid = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none"
      ) +
      labs(
        title = "Impact of Insurance",
        subtitle = "Diagnostic Gap"
      )
    )
  ) + #A
  
  wrap_elements(heatmap +
    dashboard_theme +
    labs (fill = "% Uninsured") +
    theme(
      panel.grid = element_blank()
    )
  ) + #B
  
  plot_layout(design = d2_layout) +
  
  plot_annotation(
    title = "Structural Barriers & Intersectionality",
    subtitle = "How poverty and race intersect to create gaps in health insurance coverage",
    caption = "Source: NHANES 2007-2018",
    theme = theme(
      plot.title = element_text(size = 26, face = "bold", color = "#2C3E50"),
      plot.subtitle = element_text(size = 20, color = "grey40", margin = margin(b = 20))
    )
  )

ggsave(
  filename = "../infography/panel2_structural_barriers.png",
  plot = d2,
  width = 16,
  height = 9,
  dpi = 300,
  bg = "white"
)
```

## Panel 3

```{r}
d3 <- df_viz %>%
  filter(ckd_biomarker == "Positive") %>%
  group_by(nhanes_cycle) %>%
  count(ckd_diagnosed) %>%
  mutate(
    pct = n /sum(n) *100,
    label_text = paste0(round(pct, 1), "%")
  ) %>%
filter(ckd_diagnosed == "Undiagnosed / Not aware") %>%
  
  ggplot(
    aes(
      x = nhanes_cycle,
      y = pct,
      group = 1
    )
  ) +
  
  geom_line(
    color = "grey60",
    size = 1
  ) +
  
  geom_point(
    color = "grey60",
    size = 3
  ) +
  
  ylim(65, 80) +
  
  labs(
    title = "Progress Over Time",
    subtitle = "Awareness is slowly improving, but the gap remains high.",
    x = NULL,
    y = "% Undiagnosed"
  ) +
  
  theme_minimal() +
  
  theme(
    plot.title = element_text(face = "bold"),
    axis.text.x = element_text(angle = 20)
  )

ggsave(
  filename = "../infography/panel3_trend_gap.png",
  plot = d3,
  width = 16,
  height = 9,
  dpi = 300,
  bg = "white"
)
```





## Final dashboard

```{r}
div_line <- ggplot() +
  theme_void() +
  geom_hline(yintercept = 0, color = "grey70", linewidth = 1)
```

```{r}
final_layout <- "
A
B
C
D
E
"

row_heights <- c(1, 0.05, 1, 0.05, 0.5)

d_final <-
  
  wrap_elements(d1 + plot_annotation(caption = element_blank())) + #A
  div_line + #B
  wrap_elements(d2 + plot_annotation(caption = element_blank())) + #C
  div_line + #D
  wrap_elements(d3 + dashboard_theme + labs(subtitle = "The diagnostic gap is slowly narrowing") + theme(plot.title.position = "plot", axis.title.y = element_blank(), plot.title = element_text(size = 26, color = "#2C3E50"))) + #E
  
  
  
  
  plot_layout(design = final_layout,
              heights = row_heights,
              axes = "collect") +
  
  plot_annotation(
    title = "CHRONIC KIDNEY DISEASE IN THE US: GAPS & BARRIERS",
    subtitle = "Analysis of Diagnostic Awareness and Socioeconomic Barriers",
    caption = "Source: NHANES 2007-2018\nAuthors: Gabriel Torres, Pablo Longán, David Hidalgo",
    theme = theme(
      plot.title = element_text(
        size = 30,
        face = "bold",
        family = "sans",
        margin = margin(t = 50),
        hjust = 0.5
      ),
      plot.subtitle = element_text(
        size = 24,
        color = "grey40",
        family = "sans",
        margin = margin(b = 50),
        hjust = 0.5
      ),
      plot.caption = element_text(
        size = 16,
        color = "grey40",
        family = "sans")
    )
  )

# Save
ggsave(
  filename = "../infography/Final_Infography.png",
  plot = d_final,
  width = 16,   # Panoramic
  height = 24,  # VERY HIGH so that all 3 can fit without being squashed
  dpi = 300,
  bg = "white",
  limitsize = FALSE # Allows you to save large images
)
```